ALTER TABLE "Session"
ADD COLUMN "cashierSalary" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN "serviceSalary" DOUBLE PRECISION NOT NULL DEFAULT 1200,
ADD COLUMN "baseLicenseCost" DOUBLE PRECISION NOT NULL DEFAULT 1200,
ADD COLUMN "maintenanceCost" DOUBLE PRECISION NOT NULL DEFAULT 400,
ADD COLUMN "interestRate" DOUBLE PRECISION NOT NULL DEFAULT 0.12;
