ALTER TABLE "Session"
ADD COLUMN "cashierSalary" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN "serviceSalary" DOUBLE PRECISION NOT NULL DEFAULT 1200,
ADD COLUMN "licenseCostBase" DOUBLE PRECISION NOT NULL DEFAULT 500;
